name: Release

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install wheel setuptools

      - name: Build wheel
        run: python setup.py bdist_wheel --universal

      - name: Upload Python wheel
        uses: actions/upload-artifact@v2
        with:
          name: Python wheel
          path: ${{github.workspace}}/dist/lungtumormask-*.whl
          if-no-files-found: error
